version: '2'
services:
  app:
    build: ./app
    container_name: "mongoapp"
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    # command: 
      
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db